sonar.projectKey=WebAppBookLibrary1
sonar.working.directory=C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary
sonar.pullrequest.cache.basepath=C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary
sonar.sources=\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.vs\\WebAppBookLibrary\\config\\applicationhost.config",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.vs\\WebAppBookLibrary\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.vs\\WebAppBookLibrary\\v17\\DocumentLayout.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.vs\\WebAppForeCastSolution\\config\\applicationhost.config",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.vs\\WebAppForeCastSolution\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.vs\\WebAppForeCastSolution\\v17\\DocumentLayout.json"

3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.projectKey=WebAppBookLibrary1:3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B
3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.projectName=WebAppBookLibrary
3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.projectBaseDir=C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary
3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.sourceEncoding=utf-8
3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.tests=
3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.sources=\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Controllers\\AuthController.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Controllers\\BooksController.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Controllers\\LoansController.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Controllers\\LogController.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Data\\ApplicationDbContext.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Models\\Book.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Models\\Loan.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Models\\LogEntry.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Models\\User.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Program.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\BookService.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\DummyAuthHandler.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\EmailValidator.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\LoanService.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\Logservice.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\MongoDBService.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\PasswordHasher.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\PasswordValidator.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Services\\UserService.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\WeatherForecast.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\WebAppBookLibrary.GlobalUsings.g.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\WebAppBookLibrary.AssemblyInfo.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\WebAppBookLibrary.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\appsettings.Development.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\appsettings.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\WebAppBookLibrary.http",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\Properties\\launchSettings.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\project.assets.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\WebAppBookLibrary.csproj.nuget.dgspec.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\WebAppForeCast.csproj.nuget.dgspec.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\bin\\Debug\\net8.0\\WebAppBookLibrary.deps.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\bin\\Debug\\net8.0\\WebAppBookLibrary.runtimeconfig.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\bin\\Debug\\net8.0\\WebAppBookLibrary.staticwebassets.endpoints.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\bin\\Debug\\net8.0\\WebAppForeCast.deps.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\bin\\Debug\\net8.0\\WebAppForeCast.runtimeconfig.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\bin\\Debug\\net8.0\\WebAppForeCast.staticwebassets.endpoints.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\ApiEndpoints.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\EndpointInfo\\WebAppBookLibrary.json",\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\WebAppBookLibrary\\obj\\Debug\\net8.0\\EndpointInfo\\WebAppForeCast.json"

3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.sonarqube\\out\\0"
3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.sonarqube\\out\\0\\Issues.json"
3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.cs.scanner.telemetry=\
"C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.sonarqube\\out\\0\\Telemetry.json"

3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B.sonar.working.directory=C:\\Users\\pandr\\source\\repos\\WebAppBookLibrary\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=3E29FA70-3E5E-4C96-A7E3-36CCC43E0A2B

